[package]
name = "eris-tests"
version = "1.0.0"
authors = ["devs <devs@erisprotocol.com>"]
edition = "2021"
repository = "https://github.com/erisprotocol/contracts-terra"
homepage = "https://erisprotocol.com"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

X-whitewhale-X = []
X-kujira-X = []
X-injective-X = []
X-osmosis-X = []
X-sei-X = []

default = ["X-kujira-X"]

# [net]
# git-fetch-with-cli = true
# set CARGO_NET_GIT_FETCH_WITH_CLI=true

[dependencies]
cw2 = "1.1.0"
cw20 = "1.1.0"
cw20-base = { version = "1.1.0", features = ["library"] }
cw3 = "1.1.0"
cw3-fixed-multisig = "1.1.0"
cw4-stake = "1.1.0"
cw-utils = "1.0.1"

cosmwasm-std = "1.1.3"

cosmwasm-schema = "1.1.3"
cw-multi-test = "0.16.5"
# cw-multi-test = { git = "https://github.com/CosmWasm/cw-multi-test.git",  default-features = false, features = ["iterator"], rev = "9af32fd42efcf28e9a79987f2c2036f879cd5331"}
# cw-multi-test = { git = "https://github.com/erisprotocol/cw-multi-test.git", default-features = false, features = [
#     "iterator",
# ], rev = "5f2f7062187d762b71fd22b91157c4e88de87a64" }
cw-storage-plus = "0.15.1"

astroport = { git = "https://github.com/astroport-fi/astroport-core.git", default-features = false, rev = "3b44a4044b823a145730f66ffaf7ae4205b2cd35" }

eris = { path = "../eris" }
eris-chain-adapter = { path = "../eris-chain-adapter" }

eris-arb-vault = { path = "../../contracts/arb-vault", package = "eris-arb-vault-kujira" }
eris-staking-hub = { path = "../../contracts/dao-lst", package = "eris-dao-lst-kujira" }
eris-gov-voting-escrow = { path = "../../contracts/amp-governance/voting_escrow" }
eris-gov-prop-gauges = { path = "../../contracts/amp-governance/prop_gauges" }

stader = { git = "https://github.com/stader-labs/lunax.git", package = "staking", default-features = false, rev = "20143548e2dea807b343fe6ad60375086af35ea9" }
stader-reward = { git = "https://github.com/stader-labs/lunax.git", package = "reward", default-features = false, rev = "20143548e2dea807b343fe6ad60375086af35ea9" }
steak-hub = { git = "https://github.com/PFC-developer/steak-contracts.git", package = "pfc-steak-hub-tf", default-features = false, rev = "425818764da1c6b87080b99f47ecebcccbc99dd8" }
steak = { git = "https://github.com/PFC-developer/steak-contracts.git", package = "pfc-steak", default-features = false, rev = "425818764da1c6b87080b99f47ecebcccbc99dd8" }


kujira = "0.7.13"
osmosis-std = "0.15.3"
sei-cosmwasm = { version = "0.4.10" }
sei-integration-tests = { version = "0.4.10" }

anyhow = "1"

# [dev-dependencies]
manta-stake = { git = "https://github.com/MantaDAO/manta-contracts.git", package = "cw4-stake" }
manta-cw20 = { git = "https://github.com/MantaDAO/manta-contracts.git", package = "cw20" }
manta-cw3 = { git = "https://github.com/MantaDAO/manta-contracts.git", package = "cw3-flex-multisig" }
